name: pokedex_flutter
description: "Pokedex app made with Flutter"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  boxy: ^2.2.2
  flutter:
    sdk: flutter
  animations: ^2.1.1
  cached_network_image: ^3.4.1
  dio: ^5.9.1
  flutter_riverpod: ^3.2.1
  freezed_annotation: ^3.1.0
  galleryimage: ^2.0.1
  google_fonts: ^8.0.2
  json_annotation: ^4.10.0
  material_symbols_icons: ^4.2906.0
  riverpod_annotation: ^4.0.2
  shared_preferences: ^2.5.4
  go_router: ^17.1.0
  intl: ^0.20.2
  collection: ^1.19.1
  vector_math: ^2.2.0
  flutter_svg: ^2.2.3
  image_picker: ^1.2.1
  graphql_flutter: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  json_serializable: ^6.12.0
  riverpod_generator: ^4.0.3
  riverpod_lint: ^3.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/type_logos/
